#!/bin/bash
echo "================================================================="
echo "       HOW TO ADD AUTHORIZED DOMAINS (Fix 'Blocked request')"
echo "================================================================="
echo ""
echo "If you are using ngrok or a custom domain and see 'Blocked request',"
echo "you must add the domain to the Firebase Console manually."
echo ""
echo "1. Go to Firebase Console: https://console.firebase.google.com/"
echo "2. Select project: civiclink-61370"
echo "3. Navigate to: Authentication -> Settings -> Authorized domains"
echo "4. Click 'Add domain'"
echo "5. Enter your ngrok domain (e.g., abcdef123.ngrok-free.app)"
echo "6. Click 'Add'"
echo ""
echo "For Google Drive OAuth:"
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo "2. Navigate to: APIs & Services -> Credentials"
echo "3. Edit your OAuth 2.0 Client ID"
echo "4. Add your ngrok URL to 'Authorized redirect URIs'"
echo "   (e.g., https://abcdef123.ngrok-free.app/auth/drive/callback)"
echo ""
echo "================================================================="
